INFO     root:data_depend.py:37 提取变量：errorFileId: 378819dc-28f6-4039-8043-6092f7540a43
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!