INFO     root:data_depend.py:37 提取变量：errorFileId: 8636d68b-b9fa-43af-832a-2cf0444e3856
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!