INFO     root:data_depend.py:37 提取变量：errorFileId: f2b13d41-4065-452b-8f78-942321eb4dee
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!