INFO     root:data_depend.py:37 提取变量：errorFileId: 5ff2195f-7c7e-4b1c-838d-8cd2d51ca2fa
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!