INFO     root:validate.py:76 响应断言:  预期值: '404' 实际值: '404', 断言成功!